# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.URLField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSearch',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=100)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server.ResponseServer')),
            ],
        ),
    ]
